workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: br.com.foodconsulting.app
      vars:
        BUNDLE_ID: "br.com.foodconsulting.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        # App Store Connect API keys configured in Codemagic UI
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gabrielcustodiooliveira@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "br.com.foodconsulting.app"
      flutter: stable
      java: 11
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build appbundle
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gabrielcustodiooliveira@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: Encrypted(...) # Add your Google Play Console credentials
        track: internal
        submit_as_draft: true
